### PR TITLE
Fixes reflectors not deteriorating

### LINKED ISSUE #24: reflectors do not deteriorate
i find that every type of reflector in the game does not lose any durability no matter how much time it is next to a component this makes certain upgrades useless and a waste of money i am unsure if this is a glitch or a bug but either way it's still manageable not having to replace reflectors

### PR DESCRIPTION
**Pull request by asl97**
Fixes #24

### CODE REVIEW

File: js/app.js [hunk 1]
```diff
@@ -1984,7 +1984,7 @@ var _game_loop = function() {
 					heat_add += tile.heat;
 					tile.setTicks(tile.ticks - 1);
 
-					if ( tile.reflectors.size ) {
+					if ( tile.reflectors.length ) {
```
Comment (asl97) [inline js/app.js:1987]: size was from the Set object, must have replaced it at some point and missed it here
